"""add_is_settled_to_expenses

Revision ID: 3d8a3db5bef4
Revises: 70ddfa6186c7
Create Date: 2026-07-04 18:46:34.180669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8a3db5bef4'
down_revision: Union[str, Sequence[str], None] = '70ddfa6186c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
