"""add_refresh_tokens_table

Revision ID: 4c026c14b72f
Revises: 3d8a3db5bef4
Create Date: 2026-07-05 11:00:17.651389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c026c14b72f'
down_revision: Union[str, Sequence[str], None] = '3d8a3db5bef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
